build:
    nodes:
        analysis:
            environment:
                php: 8.1
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]

tools:
    external_code_coverage: true

checks:
    php:
        excluded_dependencies:
          - phpstan/phpstan

        code_rating: true
        duplication: true
filter:
    paths:
        - src/*
