tools:
    external_code_coverage: true

checks:
    php:
        excluded_dependencies:
          - phpstan/phpstan

        code_rating: true
        duplication: true
filter:
    paths:
        - src/*
