build:
    nodes:
        php71:
            environment:
                php: 7.1
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]

tools:
    external_code_coverage: true

checks:
    php:
        excluded_dependencies:
          - phpstan/phpstan

        code_rating: true
        duplication: true
filter:
    paths:
        - src/*
